# list of users who should never be kicked. 
# important to add room admins or service/bot accounts.
exclusion_list:
  - '@user1:server.tld'
  - '@user2:server.tld'

# list of rooms or spaces to police.
# if a space is listed here, all rooms within the space
# will be monitored, but users will only be able to be kicked
# from rooms where the bot has the power to do so!
# NOTE: this bot does not support crawling a space for subspaces!
# if your community is broken into sub-spaces, please add each sub-space
# to this list.
room_list:
  - '!sOmEsPeCiAlRoOm:server.tld'
  - '!sOmEoThErRoOm12:server.tld'
